### ISSUE TITLE
No dependency with block_progress

### ISSUE THREAD

**Issue by dvdcastro** [aduranterres/auth_joomdle#1]
Hello,

This plugin makes use of block_progress in an extensive way.

Please add it to the dependencies under the `version.php` file so admins know to have that plugin installed before using auth_joomdle.

```php
$plugin->dependencies   = array(
    'block_progress' => 2016081800
);
```

Thanks!

**Comment by aduranterres** [comment]
Hi. While Joomdle uses many plugins like block_progress, they are not real dependencies, as you only need to have them installed if you want to use the integration with them.
