### ISSUE TITLE
Moodle 3.9 - Undefined var error when suspending user

### ISSUE THREAD

**Issue by davidpesce** [aduranterres/auth_joomdle#2]
Getting the following error when attempting to suspend a user in Moodle.

![joomdle err](https://user-images.githubusercontent.com/3988068/87329004-597b1100-c504-11ea-88cc-84f5626a9f7d.png)

**Comment by aduranterres** [comment]
Thanks for the bug report. I am really sorry about the very late reply....this was fixed in recent versions.

**Comment by aduranterres** [comment]
Thanks for the bug report. I am really sorry about the very late reply....this was fixed in recent versions.
